#!/bin/bash

echo "════════════════════════════════════════════════════════════════"
echo "  Transaction Website - Firebase Setup"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✓ Frontend Firebase config updated with your credentials"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Get Firebase Service Account Key:"
echo "   • Go to: https://console.firebase.google.com/project/transaction-website/settings/serviceaccounts/adminsdk"
echo "   • Click 'Generate new private key'"
echo "   • Download the JSON file"
echo "   • Save it as: backend/serviceAccountKey.json"
echo ""
echo "2. Enable Firebase Services:"
echo "   • Authentication: https://console.firebase.google.com/project/transaction-website/authentication"
echo "     → Enable Email/Password sign-in"
echo "   • Firestore: https://console.firebase.google.com/project/transaction-website/firestore"
echo "     → Create database (production mode)"
echo "   • Storage: https://console.firebase.google.com/project/transaction-website/storage"
echo "     → Get started"
echo ""
echo "3. Create Admin User:"
echo "   • Go to Authentication → Users → Add user"
echo "   • Email: admin@example.com (or your email)"
echo "   • Set a password"
echo ""
echo "4. Run the app:"
echo "   npm run server:dev    # Terminal 1"
echo "   npm start             # Terminal 2"
echo ""
echo "════════════════════════════════════════════════════════════════"
